configuration:

  dependencies:
    - "mvn://org.python:jython-standalone:2.7.1"
    - "mvn://com.walmartlabs.concord.plugins:git:0.70.0"
    - "mvn://com.walmartlabs.concord.plugins.basic:smtp-tasks:0.96.0"
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"

  arguments:
    baseUrl: "https://ci.falcon.walmart.com"
    appSecretLooper: "uconfig-automation"
    environment: "dev"
    suite: "SmokeTest"
    jobName: "/CustomerTransaction/Cloud-Powered-Checkout/CPC-uConfig-Automation/"
    looperUserName: "a0g0hwe"

flows:
# Run the default flow when someone runs the concord job manaully
  default:
    - log: "Please perform deployment via KITT file!!!"
    - call: runBuild
    - if: ${looperJob.status != "SUCCESS"}
      then:
        - log: "Automation test cases failed"
        - ${misc.throwRuntimeException("Testing Job failed")}

  #############################################################################
  # Run the fromWCNP flow when its call from uConfig Kitt.yml as part of automation"
  fromWCNP:
    - log: "Inside from WCNP. Process ID is "
    - call: runAutomation

    - if: ${looperJob.status != "SUCCESS"}
      then:
        - log: "Automation test cases failed"
        - ${misc.throwRuntimeException("Testing Job failed")}


  runAutomation:
    - log: "Triggering the automation looper job for uConfig"
    - log: "uConfig Automation URL is : ${baseUrl}/${jobName}"
    - task: looper
      in:
        baseUrl: ${baseUrl}
        jobName: ${jobName}
        username: ${looperUserName}
        apiToken: ${crypto.decryptString("3RRc9tA87Inbzl+DxyjM1jeXPONDftrwm+IGUPQTkVO9DOnkaeI6sYu9OCFbh4PM")}
        sync: true
        call: "default"
        parameters:
          environment: ${environment}
          suite: ${suite}

  runBuild:
    - log: "Triggering the automation looper job for uConfig"
    - log: "uConfig Automation URL is : ${baseUrl}/${jobName}"
    - task: looper
      in:
        baseUrl: ${baseUrl}
        jobName: ${jobName}
        username: ${looperUserName}
        apiToken: ${crypto.decryptString("3RRc9tA87Inbzl+DxyjM1jeXPONDftrwm+IGUPQTkVO9DOnkaeI6sYu9OCFbh4PM")}
        sync: true
        parameters:
          environment: ${environment}
          suite: ${suite}

  buildProcess:
    - log: "Inside build Process. Process ID is ${txId}"
    - call: runBuild